name: Setup & run Gradle

description: Setup Java & Gradle & run a Gradle command

inputs:
  java:
    default: '21'
    description: Java version
  gradle-args:
    required: true
    description: Gradle arguments

runs:
  using: composite
  steps:
    - name: Setup Java ${{ inputs.java }}
      id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java }}
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos'
      shell: bash
      run: chmod +x gradlew

    - name: Run Gradle
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      shell: bash
      run: ./gradlew ${{ inputs.gradle-args }}
