[versions]
junit-bom = '5.8.2'
reactivestreams = '1.0.3'
checkerframework = '3.21.4'
gson = '2.9.0'
jackson = '2.13.2'
protobuf = '3.12.2'
errorprone = '2.13.1'
brotli-dec = '0.1.2'
okhttp = '5.0.0-alpha.7'
jmh = '1.35'
reactor = '3.4.17'
nullaway = '0.9.6'
jaxb = '2.3.1'
moxy = '2.7.6'
jsoup = '1.14.3'
testng = '7.5'
jimfs = '1.2'
assertj = '3.22.0'
awaitility = '4.2.0'
hamcrest = '2.2'
springboot = '2.6.6'
autoservice = '1.0.1'
bson4jackson = '2.13.1'
jacoco = '0.8.8'

[libraries]
junit-bom = { module = 'org.junit:junit-bom', version.ref = 'junit-bom' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter' }
junit-platform-commons = { module = 'org.junit.platform:junit-platform-commons' }
reactivestreams-tck-flow = { module = 'org.reactivestreams:reactive-streams-tck-flow', version.ref = 'reactivestreams' }
reactivestreams = { module = 'org.reactivestreams:reactive-streams', version.ref = 'reactivestreams' }
reactivestreams-examples = { module = 'org.reactivestreams:reactive-streams-examples', version.ref = 'reactivestreams' }
checkerframework = { module = 'org.checkerframework:checker', version.ref = 'checkerframework' }
checkerframework-qual = { module = 'org.checkerframework:checker-qual', version.ref = 'checkerframework' }
gson = { module = 'com.google.code.gson:gson', version.ref = 'gson' }
jackson-databind = { module = 'com.fasterxml.jackson.core:jackson-databind', version.ref = 'jackson' }
protobuf-java = { module = 'com.google.protobuf:protobuf-java', version.ref = 'protobuf' }
protobuf-compiler = { module = 'com.google.protobuf:protoc', version.ref = 'protobuf' }
errorprone = { module = 'com.google.errorprone:error_prone_core', version.ref = 'errorprone' }
errorprone-annotations = { module = 'com.google.errorprone:error_prone_annotations', version.ref = 'errorprone' }
brotli-dec = { module = 'org.brotli:dec', version.ref = 'brotli-dec' }
mockwebserver = { module = 'com.squareup.okhttp3:mockwebserver3', version.ref = 'okhttp' }
jmh-core = { module = 'org.openjdk.jmh:jmh-core', version.ref = 'jmh' }
jmh-annprocess = { module = 'org.openjdk.jmh:jmh-generator-annprocess', version.ref = 'jmh' }
okhttp-tls = { module = 'com.squareup.okhttp3:okhttp-tls', version.ref = 'okhttp' }
okhttp = { module = 'com.squareup.okhttp3:okhttp', version.ref = 'okhttp' }
reactor-core = { module = 'io.projectreactor:reactor-core', version.ref = 'reactor' }
nullaway = { module = 'com.uber.nullaway:nullaway', version.ref = 'nullaway' }
jaxb-api = { module = 'javax.xml.bind:jaxb-api', version.ref = 'jaxb' }
moxy = { module = 'org.eclipse.persistence:org.eclipse.persistence.moxy', version.ref = 'moxy' }
jsoup = { module = 'org.jsoup:jsoup', version.ref = 'jsoup' }
testng = { module = 'org.testng:testng', version.ref = 'testng' }
junit-params = { module = 'org.junit.jupiter:junit-jupiter-params' }
jimfs = { module = 'com.google.jimfs:jimfs', version.ref = 'jimfs' }
assertj = { module = 'org.assertj:assertj-core', version.ref = 'assertj' }
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }
hamcrest = { module = 'org.hamcrest:hamcrest', version.ref = 'hamcrest' }
springboot-starter-web = { module = 'org.springframework.boot:spring-boot-starter-web', version.ref = 'springboot' }
autoservice-annotations = { module = 'com.google.auto.service:auto-service-annotations', version.ref = 'autoservice' }
autoservice-annprocess = { module = 'com.google.auto.service:auto-service', version.ref = 'autoservice' }
jackson-xml = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml', version.ref = 'jackson' }
jackson-protobuf = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-protobuf', version.ref = 'jackson' }
jackson-avro = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-avro', version.ref = 'jackson' }
bson4jackson = { module = 'de.undercouch:bson4jackson', version.ref = 'bson4jackson' }
