--local entryKey = KEYS[1]
--local dataVersion = ARGV[1]
--
--if dataVersion == redis.call('hget', entryKey, 'dataVersion') then
--    redis.call('hincrby', entryKey, 'openCount', -1)
--else
--    local staleDataKey = entryKey .. ':data:' .. dataVersion .. ':stale'
--    if redis.call('decr', staleDataKey .. ':openCount') <= 0 then
--        redis.call('unlink', staleDataKey, staleDataKey .. ':openCount')
--    end
--end
