name: Setup & run Gradle

description: Setup Java & Gradle & optionally run a Gradle command

inputs:
  java:
    default: '21'
    description: Java version. Set to 'GraalVM' for a GraalVM setup.
  gradle-args:
    required: false
    description: Arguments to Gradle command (optional).
  cmd:
    required: false
    description: Command to run (optional). Runs after Gradle if gradle-args is set.

runs:
  using: composite
  steps:
    - name: Setup Java 21 for Gradle
      id: setup-gradle-jdk
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin

    - name: Setup Test Java ${{ inputs.java }}
      if: inputs.java != 'GraalVM' && inputs.java != '21'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java }}
        distribution: temurin

    - name: Setup Test Java ${{ inputs.java }}
      if: inputs.java == 'GraalVM'
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: graalvm-community
        github-token: ${{ github.token }}

    - name: Verify GraalVM installation
      if: inputs.java == 'GraalVM'
      shell: bash
      run: native-image --version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable
      if: inputs.gradle-args != '' && (runner.os == 'linux' || runner.os == 'macOS')
      shell: bash
      run: chmod +x gradlew

    - name: Run Gradle command
      if: inputs.gradle-args != ''
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      shell: bash
      run: ./gradlew -PjavaVersion=${{ inputs.java }} ${{ inputs.gradle-args }}

    - name: Run command
      if: inputs.cmd != ''
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      shell: bash
      run: |
        ${{ inputs.cmd }}
