name: Setup & run Gradle

description: Setup Java & Gradle & optionally run a Gradle command

inputs:
  java:
    default: '21'
    description: Java version
  gradlew:
    required: false
    description: Arguments to Gradle command (optional)

runs:
  using: composite
  steps:
    - name: Setup Java ${{ inputs.java }}
      id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java }}
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      if: inputs.gradle-args != '' && (runner.os == 'linux' || runner.os == 'macOS')
      shell: bash
      run: chmod +x gradlew

    - name: Run Gradle command
      if: ${{ inputs.gradle-args }} != ''
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      shell: bash
      run: ./gradlew ${{ inputs.gradle-args }}
