name: Dependency Submission

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate & submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          additional-arguments: -PincludeNativeTests
